service: api
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: src/handler.default
    events:
      - httpApi:
          path: /
          method: get
