service: api
useDotenv: true
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    events:
      - http:
          authorizer: auth
          path: graphql
          method: post
    handler: src/handlers/api.default
  auth:
    handler: src/handlers/auth.default
